Sprint 1
likeariverstream/middle.messenger.praktikum.yandex pull request #1
Opened 2023-02-13 20:08 UTC by likeariverstream

2023-02-14 12:03 UTC, evgenygil requested changes

2023-02-14 18:37 UTC, likeariverstream commented on package.json
> +  "description": "---",
Удалил description)

2023-02-14 18:47 UTC, likeariverstream commented on server.js
> +const port = 3000
Исправил

2023-02-14 18:47 UTC, likeariverstream commented on src/pages/404/404.hbs
> +    {{> error/error class="error" message="Страница не найдена"}}
Поместил контент в тег main

2023-02-14 18:47 UTC, likeariverstream commented on src/pages/register/register.hbs
> +        {{> input/input class="input"  placeholder="Подтвердите пароль" name="confirm" type="password"}}
Исправил

2023-02-16 09:17 UTC, evgenygil approved these changes

2023-02-16 09:17 UTC, evgenygil commented on data/chats.json
> +{
А что здесь подразумевается? Зачем пустой файл?

2023-02-16 09:17 UTC, evgenygil commented on src/index.css
> +            color: #777;
Можно цвета занести в переменные, это чисто улучшение, не баг конечно, но потом удобнее будет оперировать цветами не копипастя код цвета

2023-02-16 10:03 UTC, likeariverstream commented on data/chats.json
> +{
Удалил)

2023-02-16 10:03 UTC, likeariverstream commented on src/index.css
> +            color: #777;
Спасибо, это исправлю тоже

2023-02-16 10:04 UTC, merged